<ips:template parameters="$tab" />
<li>
	<a href='{url="app=teamspeak&module=teamspeak&controller=membersync" seoTemplate="teamspeak_member_sync"}' id='setting_tsuid' class='ipsType_normal ipsSideMenu_item {{if $tab === 'tsuid'}}ipsSideMenu_itemActive{{endif}}' title="{lang="teamspeak_uuid_setting"}" role="tab" aria-selected="false">
	<i class='fa fa-phone'></i> {lang="teamspeak_uuid_setting"}
	</a>
</li>