<ips:template parameters="$content, $orientation='horizontal'" />
<h3 class="ipsWidget_title ipsType_reset">{lang="teamspeak_viewer"}</h3>
{{if is_array( $content )}}
	{{$jsName = $content['jsName'];}}
	{{$serverIcon = $content['icon'];}}
	{{$serverName = $content['name'];}}
	{{$channels = $content['channels'];}}

	<div class='{{if $orientation == 'vertical'}}ipsPad{{endif}}'>
		<div class="ts3ssv">
			<input type="hidden" id="ts3ssv-{$jsName}-hostport" value="{setting='teamspeak_server_ip'}:{setting='teamspeak_virtual_port'}" />
			<div class="ts3ssvItem ts3ssvServer">
				<a href="javascript:ts3ssvconnect('{$jsName}')"><i class="tsviewer tsviewer-{$serverIcon}" ></i>{$serverName}</a>
				{template="teamspeakViewerChannels" group="widgets" location="front" app="teamspeak" params="$channels"}
			</div>
		</div>
	</div>
{{else}}
	<div class="ts3ssvError">
		$content
	</div>
{{endif}}